#pragma once
#include <string>
#include <vector>

class Song
{
private:
    /* DATA NEEDED FOR OUTPUT */
    std::string id;                       //Primary identifier for the track, generated by Spotify
    std::string name;                     //The title of the track
    std::vector<std::string> artists;     //The list of artists credited for production of the track
    int duration_ms;                      //The length of the track in seconds
    float distance;                       //Final Parameter we are interested in

    /* USER INPUT PARAMETERS */
    bool _explicit;                       //Whether the track contains explicit content or not
    float acousticness;                   //Metric of the track being acoustic
    float danceability;                   //Metric of the track being danceable
    float energy;                         //Metric of the energy of the track
    float instrumentalness;               //Metric of the track being instrumental
    float liveness;                       //Metric of the track sounding as a live performance
    float speechiness;                    //Metric of the track containing human voice
    float happiness;                      //Metric of the positiveness of the track
    float tempo;                          //The tempo of the track in BPM as its reciprocal

public:

    //Constructor
    Song(std::string acousticness, std::string artists, std::string danceability, std::string duration_ms, std::string energy, std::string _explicit, std::string id, std::string instrumentalness, std::string liveness, std::string name, std::string speechiness, std::string tempo, std::string happiness)
    {
        this->acousticness = stoi(acousticness);
        int parseLocation = 0, beg = 0, end = 0, offset = 0;
        std::vector<std::string> a;

        while (parseLocation != -1 || parseLocation != artists.size() - 1)
        {
            beg = artists.find("'", parseLocation);
            end = artists.find("'", beg + 1);
            if (end == -1)
            {
                end = artists.find("'", end + 1);
            }
            //No else because the above corrects the case where the name has an apostrophe in it already
            if (end != -1)
            {
                a.push_back(artists.substr(beg + 1, end - 1));
            }
            parseLocation = end + 1;
        }

        this->acousticness = stof(acousticness);
        this->artists = a;
        this->danceability = stof(danceability);
        this->duration_ms = (int)(stof(duration_ms) / 1000);
        this->energy = stof(energy);
        this->_explicit = (_explicit == "1") ? true : false;
        this->id = id;
        this->instrumentalness = stof(instrumentalness);
        this->liveness = stof(liveness);
        this->name = name;
        this->speechiness = stof(speechiness);
        this->tempo = 1 / stof(tempo);
        this->happiness = stof(happiness);
        this->distance = 0.0f;
    }

    //Getters
    float getAcousticness() { return acousticness; }
    std::vector<std::string> getArtists() { return artists; }
    float getDanceability() { return danceability; }
    int getDuration() { return duration_ms; }
    float getEnergy() { return energy; }
    bool getExplicit() { return _explicit; }
    std::string getID() { return id; }
    float getInstrumentalness() { return instrumentalness; }
    float getLiveness() { return liveness; }
    std::string getName() { return name; }
    float getSpeechiness() { return speechiness; }
    float getTempo() { return tempo; }
    float getHappiness() { return happiness; }
    float getDistance() { return distance; }
};